package services

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"text/template"
	"time"

	"gorm.io/gorm"

	"github.com/asdl/hub/internal/models"
)

type NginxService struct {
	db     *gorm.DB
	domain string
}

func NewNginxService(db *gorm.DB) *NginxService {
	return &NginxService{
		db:     db,
		domain: os.Getenv("HUB_DOMAIN"),
	}
}

const nginxConfigTemplate = `
# Auto-generated by ASDL Hub - DO NOT EDIT MANUALLY
# Last updated: {{.Timestamp}}

{{range .Containers}}
server {
    listen 80;
    server_name {{.Domain}};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name {{.Domain}};

    ssl_certificate /etc/letsencrypt/live/{{.HubDomain}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{.HubDomain}}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://{{.NodeIP}}:{{.Port}};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
{{end}}
`

type ContainerRoute struct {
	Domain    string
	HubDomain string
	NodeIP    string
	Port      string
}

type NginxData struct {
	Timestamp  string
	Containers []ContainerRoute
}

func (s *NginxService) UpdateNginxConfig() error {
	if s.domain == "" {
		log.Println("⚠️ HUB_DOMAIN not set, skipping nginx update")
		return nil
	}

	log.Println("🔄 Updating Nginx config...")

	var projects []models.Project
	s.db.Where("status = ? AND domain != ?", "running", "").Find(&projects)
	log.Printf("Found %d running projects with domains", len(projects))

	var routes []ContainerRoute

	for _, project := range projects {
		if project.Domain == "" {
			continue
		}

		var node models.Node
		if err := s.db.First(&node, "id = ?", project.NodeID).Error; err != nil {
			log.Printf("⚠️ Node not found for project %s: %v", project.Name, err)
			continue
		}

		port := "8000"
		if len(project.Ports) > 0 {
			parts := strings.Split(project.Ports[0], ":")
			if len(parts) == 2 {
				port = parts[0]
			}
		}

		routes = append(routes, ContainerRoute{
			Domain:    project.Domain,
			HubDomain: s.domain,
			NodeIP:    node.VPNIP,
			Port:      port,
		})
	}

	if len(routes) == 0 {
		log.Println("No projects with domains found, skipping Nginx update")
		return nil
	}

	data := NginxData{
		Timestamp:  time.Now().Format(time.RFC3339),
		Containers: routes,
	}

	tmpl, err := template.New("nginx").Parse(nginxConfigTemplate)
	if err != nil {
		return err
	}

	tmpFile := "/tmp/nginx-asdl.conf"
	f, err := os.Create(tmpFile)
	if err != nil {
		return err
	}

	if err := tmpl.Execute(f, data); err != nil {
		f.Close()
		return err
	}
	f.Close()

	if err := exec.Command("sudo", "cp", tmpFile, "/etc/nginx/sites-available/asdl-auto.conf").Run(); err != nil {
		return err
	}

	symlinkPath := "/etc/nginx/sites-enabled/asdl-auto.conf"
	if _, err := os.Lstat(symlinkPath); os.IsNotExist(err) {
		if err := exec.Command("sudo", "ln", "-s",
			"/etc/nginx/sites-available/asdl-auto.conf",
			symlinkPath,
		).Run(); err != nil {
			return fmt.Errorf("failed to create sites-enabled symlink: %w", err)
		}
		log.Println("🔗 Created sites-enabled symlink for asdl-auto.conf")
	}

	if err := exec.Command("sudo", "nginx", "-t").Run(); err != nil {
		return fmt.Errorf("nginx config test failed: %w", err)
	}

	if err := exec.Command("sudo", "systemctl", "reload", "nginx").Run(); err != nil {
		return fmt.Errorf("failed to reload nginx: %w", err)
	}

	log.Printf("✅ Nginx config updated with %d routes", len(routes))
	return nil
}
