package services

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"sync"
	"text/template"
	"time"

	"gorm.io/gorm"

	"github.com/asdl/hub/internal/models"
)

// The installer creates these: a directory the hub may write, included from
// nginx's http block, a webroot for ACME challenges, and a root-owned helper
// the hub may run with sudo to issue a certificate for one domain.
const (
	defaultRoutesDir   = "/etc/nginx/asdl-hub.d"
	defaultACMEWebroot = "/var/www/asdl-acme"
	defaultCertHelper  = "/usr/local/lib/asdl-hub/issue-cert"
	letsEncryptLiveDir = "/etc/letsencrypt/live"
	certbotSSLOptions  = "/etc/letsencrypt/options-ssl-nginx.conf"

	// Let's Encrypt allows only a few failed validations per hour, so a
	// domain whose DNS isn't pointed here yet is retried at most this often.
	certRetryInterval = 10 * time.Minute
)

type NginxService struct {
	db          *gorm.DB
	routesDir   string
	acmeWebroot string
	certHelper  string

	// mu serializes config updates; deploys, failovers and the API can all
	// trigger one at the same time.
	mu sync.Mutex
	// certs remembers domains with an issued certificate, and certFailed when
	// issuing one last failed.
	certs      map[string]bool
	certFailed map[string]time.Time
}

func NewNginxService(db *gorm.DB) *NginxService {
	return &NginxService{
		db:          db,
		routesDir:   envOr("NGINX_ROUTES_DIR", defaultRoutesDir),
		acmeWebroot: envOr("ACME_WEBROOT", defaultACMEWebroot),
		certHelper:  envOr("CERT_HELPER", defaultCertHelper),
		certs:       make(map[string]bool),
		certFailed:  make(map[string]time.Time),
	}
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

const nginxConfigTemplate = `# Auto-generated by ASDL Hub - DO NOT EDIT MANUALLY
# Last updated: {{.Timestamp}}

map $http_upgrade $asdl_connection_upgrade {
    default upgrade;
    ''      close;
}
{{range .Routes}}
server {
    listen 80;
    listen [::]:80;
    server_name {{.Domain}};

    location /.well-known/acme-challenge/ {
        root {{$.ACMEWebroot}};
    }
{{- if .TLS}}

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {{.Domain}};

    ssl_certificate {{$.CertDir}}/{{.Domain}}/fullchain.pem;
    ssl_certificate_key {{$.CertDir}}/{{.Domain}}/privkey.pem;
{{- if $.SSLOptions}}
    include {{$.SSLOptions}};
{{- end}}
{{- end}}

    location / {
        proxy_pass http://{{.NodeIP}}:{{.Port}};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $asdl_connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
{{end}}`

var nginxTemplate = template.Must(template.New("nginx").Parse(nginxConfigTemplate))

type ContainerRoute struct {
	Domain string
	NodeIP string
	Port   string
	TLS    bool
}

type NginxData struct {
	Timestamp   string
	ACMEWebroot string
	CertDir     string
	SSLOptions  string
	Routes      []ContainerRoute
}

// UpdateNginxConfig regenerates the routes for all running projects that
// have a domain, then tries to issue certificates for domains that lack one
// and switches those to HTTPS.
func (s *NginxService) UpdateNginxConfig() error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if info, err := os.Stat(s.routesDir); err != nil || !info.IsDir() {
		log.Printf("⚠️ Nginx routes directory %s not found, skipping nginx update (re-run the installer to create it)", s.routesDir)
		return nil
	}

	routes, err := s.routes()
	if err != nil {
		return err
	}
	if err := s.apply(routes); err != nil {
		return err
	}

	// The HTTP blocks written above serve the ACME challenge, so certificates
	// can be requested now. Issuing one can take a few seconds per domain.
	issued := false
	for i := range routes {
		if !routes[i].TLS && s.issueCert(routes[i].Domain) {
			routes[i].TLS = true
			issued = true
		}
	}
	if issued {
		return s.apply(routes)
	}
	return nil
}

func (s *NginxService) routes() ([]ContainerRoute, error) {
	var projects []models.Project
	if err := s.db.Where("status = ? AND domain != ?", "running", "").Find(&projects).Error; err != nil {
		return nil, fmt.Errorf("failed to load projects: %w", err)
	}

	var routes []ContainerRoute
	seen := make(map[string]bool)
	for _, project := range projects {
		if seen[project.Domain] {
			log.Printf("⚠️ Domain %s is used by more than one project, skipping %s", project.Domain, project.Name)
			continue
		}
		var node models.Node
		if err := s.db.First(&node, "id = ?", project.NodeID).Error; err != nil {
			log.Printf("⚠️ Node not found for project %s: %v", project.Name, err)
			continue
		}
		seen[project.Domain] = true
		routes = append(routes, ContainerRoute{
			Domain: project.Domain,
			NodeIP: node.VPNIP,
			Port:   project.HostPort(),
			TLS:    s.hasCert(project.Domain),
		})
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].Domain < routes[j].Domain })
	return routes, nil
}

// apply writes the routes file, checks it with nginx -t and reloads nginx.
// If nginx rejects the config, the previous file is put back.
func (s *NginxService) apply(routes []ContainerRoute) error {
	data := NginxData{
		Timestamp:   time.Now().Format(time.RFC3339),
		ACMEWebroot: s.acmeWebroot,
		CertDir:     letsEncryptLiveDir,
		Routes:      routes,
	}
	if _, err := os.Stat(certbotSSLOptions); err == nil {
		data.SSLOptions = certbotSSLOptions
	}

	var buf bytes.Buffer
	if err := nginxTemplate.Execute(&buf, data); err != nil {
		return err
	}

	path := filepath.Join(s.routesDir, "routes.conf")
	previous, readErr := os.ReadFile(path)

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write nginx routes: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("failed to install nginx routes: %w", err)
	}

	if out, err := exec.Command("sudo", "-n", "nginx", "-t").CombinedOutput(); err != nil {
		if readErr == nil {
			_ = os.WriteFile(path, previous, 0644)
		} else {
			_ = os.Remove(path)
		}
		return fmt.Errorf("nginx rejected the generated config, kept the previous one: %w\n%s", err, out)
	}
	if out, err := exec.Command("sudo", "-n", "systemctl", "reload", "nginx").CombinedOutput(); err != nil {
		return fmt.Errorf("failed to reload nginx: %w\n%s", err, out)
	}

	log.Printf("✅ Nginx config updated with %d routes", len(routes))
	return nil
}

// hasCert reports whether a certificate for domain already exists. Only the
// helper can look, since /etc/letsencrypt/live is readable by root alone.
func (s *NginxService) hasCert(domain string) bool {
	if s.certs[domain] {
		return true
	}
	if exec.Command("sudo", "-n", s.certHelper, "--check", domain).Run() == nil {
		s.certs[domain] = true
	}
	return s.certs[domain]
}

// issueCert asks the root-owned helper for a certificate for domain. The
// helper is idempotent: it succeeds straight away when a valid cert exists.
func (s *NginxService) issueCert(domain string) bool {
	if last, ok := s.certFailed[domain]; ok && time.Since(last) < certRetryInterval {
		return false
	}
	out, err := exec.Command("sudo", "-n", s.certHelper, domain).CombinedOutput()
	if err != nil {
		s.certFailed[domain] = time.Now()
		log.Printf("⚠️ Could not get a certificate for %s, serving it over HTTP for now (does its DNS point at this server?): %v\n%s", domain, err, out)
		return false
	}
	delete(s.certFailed, domain)
	s.certs[domain] = true
	log.Printf("🔒 Certificate ready for %s", domain)
	return true
}
